name: Main Taski Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.8.0
      - name: Lint with ruff and run django tests
        run: |
          python -m ruff check backend/
          cd backend/
          python manage.py test
